#!/bin/bash

# Adds new students to system

for student in "$@"
do
	echo "Adding $student..."
	sudo adduser -gecos "" --disabled-password --quiet $student
	echo ${student}:Password1 | sudo chpasswd
	sudo chmod 751 /home/${student}
done
