#!/bin/bash

# Installs packages and configures system
# This file is meant to be idempotent, so a newer version can be run on an existing system without issues

editors="vim emacs nano"
tools="git tmux gdb sqlite3 pandoc"

# Languages
python="python3 python-pip"
c="build-essential" # includes gcc, g++, and GNU make
js="nodejs npm"
r="r-base-core"
haskell="ghc"
prolog="swi-prolog"
algol="algol68g"
lisp="gcl"
scheme="mit-scheme"
ml="smlnj"
languages="$python $c $js $r $haskell $prolog $algol $lisp $scheme $ml"

sudo apt --assume-yes update
sudo apt --assume-yes remove snapd
sudo apt --assume-yes install $editors $tools $languages

# Tools not in repositories

# Micro text editor
micro_version="1.4.1"
cd /tmp && wget https://github.com/zyedidia/micro/releases/download/v$micro_version/micro-$micro_version-linux64.tar.gz
cd /tmp && tar -xvf /tmp/micro-$micro_version-linux64.tar.gz
sudo mv /tmp/micro-$micro_version/micro /usr/bin/

# ripgrep (rg)
rg_version="11.0.2"
cd /tmp && wget https://github.com/BurntSushi/ripgrep/releases/download/$rg_version/ripgrep_${rg_version}_amd64.deb
sudo dpkg -i /tmp/ripgrep_${rg_version}_amd64.deb

# fd `find` replacement
# There is a .deb for this, but it names the bin `fdfind` as `fd` is already taken by the fdclone package
# We simply grab the binary and call it `fd`. This may cause breakage on systems using fdclone, but it
# saves users from need to alias `fd` to `fdfind`
fd_version="7.4.0"
cd /tmp && wget https://github.com/sharkdp/fd/releases/download/v$fd_version/fd-v${fd_version}-x86_64-unknown-linux-gnu.tar.gz
cd /tmp && tar -xvf  fd-v$fd_version-x86_64-unknown-linux-gnu.tar.gz
sudo mv  fd-v$fd_version-x86_64-unknown-linux-gnu/fd /usr/bin/

# fzf fuzzy finder
fzf_version="0.20.0"
cd /tmp && wget https://github.com/junegunn/fzf-bin/releases/download/$fzf_version/fzf-$fzf_version-linux_amd64.tgz
cd /tmp && tar -xvf fzf-$fzf_version-linux_amd64.tgz
sudo mv /tmp/fzf /usr/bin

# Custom tools

# addstudent
cd /tmp && wget https://raw.githubusercontent.com/jncraton/ubuntu-server-student-setup/master/addstudent
sudo chmod 755 /tmp/addstudent
sudo mv /tmp/addstudent /usr/bin/

# Configure home dir privacy
chmod 750 $HOME
